sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t cosmin1000/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true cosmin1000/docker-react npm run test -- --coverage